### ISSUE TITLE
Run an uninstall-profile on uninstalling

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFQuickInstallerTool#4]
``Products.CMFQuickInstallerTool.InstalledProduct.InstalledProduct.uninstall`` should look for a and import a profile called ``uninstall`` if ``reinstall`` is ``False`` and ``getUninstallMethod`` does not find a method in ``Extensions/Install.py``. 

See https://github.com/plone/bobtemplates.plone/issues/27

**Comment by mauritsvanrees** [comment]
+1

**Comment by gyst** [comment]
+1

**Comment by djowett** [comment]
Sounds reasonable to me, but in light of the following issue below raised by @keul, it would be good to hear views from him, and maybe other participants on that thread: @datakurre & @vangheem 

https://github.com/plone/Products.CMFPlone/issues/443

**Comment by datakurre** [comment]
Uninstall profile is a weird concept, but :+1:, because we don't have any better options / proposals.

**Comment by keul** [comment]
:+1:  (well know convention over configuration!)

**Comment by vangheem** [comment]
:+1: yes please

**Comment by pbauer** [comment]
https://github.com/plone/Products.CMFQuickInstallerTool/pull/6 is ready to be merged
