### ISSUE TITLE
Doctests are not run

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFQuickInstallerTool#5]
The doctests in this package are not run. In the using Plone 5 coredev I added nonsense to the doctests and ran:

    ./bin/test -s Products.CMFQuickInstallerTool

**Comment by pbauer** [comment]
@tomgross could you maybe have a look at that?

**Comment by gforcada** [comment]
@pbauer it's half done on #7 there's something still failing on it though...

**Comment by tomgross** [comment]
https://github.com/plone/Products.CMFQuickInstallerTool/pull/8

**Comment by pbauer** [comment]
Fixed in #8
